package com.liveproduction.core.media.encoder

import android.media.MediaCodec
import android.media.MediaCodecInfo
import android.media.MediaFormat
import android.util.Log
import com.liveproduction.core.media.recording.RecordingManager
import java.nio.ByteBuffer
import java.nio.ByteOrder

class AudioEncoder(
    private val sampleRate: Int = 44100,
    private val channelCount: Int = 2,
    private val bitrateBps: Int = 128_000
) {

    private var mediaCodec: MediaCodec? = null
    @Volatile private var isEncoderRunning = false
    private var drainThread: Thread? = null
    private var audioPtsUs = 0L

    fun start() {
        val format = MediaFormat.createAudioFormat(MediaFormat.MIMETYPE_AUDIO_AAC, sampleRate, channelCount).apply {
            setInteger(MediaFormat.KEY_AAC_PROFILE, MediaCodecInfo.CodecProfileLevel.AACObjectLC)
            setInteger(MediaFormat.KEY_BIT_RATE, bitrateBps)
            setInteger(MediaFormat.KEY_MAX_INPUT_SIZE, 16384)
        }

        val codec = MediaCodec.createEncoderByType(MediaFormat.MIMETYPE_AUDIO_AAC)
        codec.configure(format, null, null, MediaCodec.CONFIGURE_FLAG_ENCODE)
        codec.start()

        mediaCodec = codec
        audioPtsUs = 0L
        isEncoderRunning = true

        drainThread = Thread {
            drainLoop(codec)
        }.apply {
            name = "AacEncoderDrainThread"
            start()
        }

        Log.i(TAG, "AudioEncoder AAC started: $sampleRate Hz, $channelCount ch, ${bitrateBps / 1000} kbps")
    }

    fun encodePcmFrame(pcmShorts: ShortArray, length: Int) {
        val codec = mediaCodec ?: return
        if (!isEncoderRunning) return

        try {
            val inputBufferIndex = codec.dequeueInputBuffer(10_000)
            if (inputBufferIndex >= 0) {
                val inputBuffer = codec.getInputBuffer(inputBufferIndex) ?: return
                inputBuffer.clear()
                inputBuffer.order(ByteOrder.LITTLE_ENDIAN)

                val maxBytesToWrite = minOf(length * 2, inputBuffer.remaining())
                val shortsToWrite = maxBytesToWrite / 2

                for (i in 0 until shortsToWrite) {
                    inputBuffer.putShort(pcmShorts[i])
                }

                val samplesInFrame = shortsToWrite / channelCount
                val durationUs = if (samplesInFrame > 0) (samplesInFrame * 1_000_000L) / sampleRate else 0L

                val pts = audioPtsUs
                audioPtsUs += durationUs

                codec.queueInputBuffer(inputBufferIndex, 0, shortsToWrite * 2, pts, 0)
            }
        } catch (e: Exception) {
            Log.w(TAG, "Error queuing PCM frame to AAC encoder", e)
        }
    }

    private fun drainLoop(codec: MediaCodec) {
        val bufferInfo = MediaCodec.BufferInfo()

        while (isEncoderRunning) {
            try {
                val outputBufferIndex = codec.dequeueOutputBuffer(bufferInfo, 10_000)
                when (outputBufferIndex) {
                    MediaCodec.INFO_OUTPUT_FORMAT_CHANGED -> {
                        // Standard GitHub Android MediaCodec Pattern:
                        // Extract output format generated by hardware MediaCodec (which contains csd-0 Audio Specific Config)!
                        val newFormat = codec.outputFormat
                        Log.i(TAG, "AAC Encoder Output Format Changed with CSD-0: $newFormat")
                        RecordingManager.getInstance().addAudioFormat(newFormat)
                    }
                    MediaCodec.INFO_TRY_AGAIN_LATER -> {}
                    else -> {
                        if (outputBufferIndex >= 0) {
                            val outputBuffer = codec.getOutputBuffer(outputBufferIndex)
                            if (outputBuffer != null) {
                                // Standard GitHub Android MediaCodec Pattern:
                                // Filter out BUFFER_FLAG_CODEC_CONFIG because csd-0 is already in MediaFormat!
                                if ((bufferInfo.flags and MediaCodec.BUFFER_FLAG_CODEC_CONFIG) != 0) {
                                    bufferInfo.size = 0
                                }

                                if (bufferInfo.size > 0) {
                                    outputBuffer.position(bufferInfo.offset)
                                    outputBuffer.limit(bufferInfo.offset + bufferInfo.size)

                                    // Write audio sample to MediaMuxer local recording
                                    RecordingManager.getInstance().writeAudioSample(outputBuffer, bufferInfo)
                                }
                            }
                            codec.releaseOutputBuffer(outputBufferIndex, false)
                        }
                    }
                }
            } catch (e: Exception) {
                if (isEncoderRunning) {
                    Log.e(TAG, "Error in AudioEncoder drainLoop", e)
                }
            }
        }
    }

    fun stop() {
        if (isEncoderRunning) {
            isEncoderRunning = false
            try {
                drainThread?.join(500)
                drainThread = null
            } catch (e: Exception) {}

            try {
                mediaCodec?.stop()
                mediaCodec?.release()
            } catch (e: Exception) {
                Log.e(TAG, "Error stopping AudioEncoder", e)
            }
            mediaCodec = null
            Log.i(TAG, "AudioEncoder AAC stopped")
        }
    }

    companion object {
        private const val TAG = "AudioEncoder"
    }
}
